name: GitHub Actions Demo
run-name: Triggered by merge pull request

on:
  pull_request:
    branches:
      - main
      
jobs:
    build-job:
      runs-on: ubuntu-latest
      env:
        FULLNAME: 'Mary Doe'
      steps:
        - run: echo ${{ vars.COMPANY_NAME }}
        - run: echo ${{ secrets.COMPANY_TOKEN }}
        - run: echo "My host is $MY_HOST and $FULLNAME $COMPANY_NAME"
        - run: echo "Hello ${{ github.actor }} $FULLNAME"

    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "Repo is ${{ github.repository }} ${{ env.MY_HOST }}"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "deploy job to production server ${{ job.status }}"
